/*
 * generated by Xtext 2.40.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.services.StateMachineGrammarAccess;
import stateMachine.CompositeState;
import stateMachine.Event;
import stateMachine.HistoryState;
import stateMachine.InitialState;
import stateMachine.State;
import stateMachine.StateMachine;
import stateMachine.StateMachinePackage;
import stateMachine.Transition;
import stateMachine.Xmod_Action;
import stateMachine.Xmod_Exception;
import stateMachine.Xmod_Operation;

@SuppressWarnings("all")
public class StateMachineSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private StateMachineGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == StateMachinePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case StateMachinePackage.COMPOSITE_STATE:
				sequence_CompositeState_Impl(context, (CompositeState) semanticObject); 
				return; 
			case StateMachinePackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case StateMachinePackage.HISTORY_STATE:
				sequence_HistoryState(context, (HistoryState) semanticObject); 
				return; 
			case StateMachinePackage.INITIAL_STATE:
				sequence_InitialState(context, (InitialState) semanticObject); 
				return; 
			case StateMachinePackage.STATE:
				sequence_State_Impl(context, (State) semanticObject); 
				return; 
			case StateMachinePackage.STATE_MACHINE:
				sequence_StateMachine(context, (StateMachine) semanticObject); 
				return; 
			case StateMachinePackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			case StateMachinePackage.XMOD_ACTION:
				sequence_Xmod_Action(context, (Xmod_Action) semanticObject); 
				return; 
			case StateMachinePackage.XMOD_EXCEPTION:
				sequence_Xmod_Exception(context, (Xmod_Exception) semanticObject); 
				return; 
			case StateMachinePackage.XMOD_OPERATION:
				sequence_Xmod_OperationDef(context, (Xmod_Operation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     State returns CompositeState
	 *     CompositeState_Impl returns CompositeState
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         states+=State* 
	 *         initialState=[InitialState|EString] 
	 *         historyState=[HistoryState|EString]? 
	 *         (actions+=Xmod_Action actions+=Xmod_Action*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_CompositeState_Impl(ISerializationContext context, CompositeState semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Event returns Event
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_Event(ISerializationContext context, Event semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateMachinePackage.Literals.EVENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateMachinePackage.Literals.EVENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEventAccess().getNameEStringParserRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     State returns HistoryState
	 *     HistoryState returns HistoryState
	 *
	 * Constraint:
	 *     name=EString
	 * </pre>
	 */
	protected void sequence_HistoryState(ISerializationContext context, HistoryState semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, StateMachinePackage.Literals.STATE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, StateMachinePackage.Literals.STATE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHistoryStateAccess().getNameEStringParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     State returns InitialState
	 *     InitialState returns InitialState
	 *
	 * Constraint:
	 *     (name=EString referencedState=[State|EString]?)
	 * </pre>
	 */
	protected void sequence_InitialState(ISerializationContext context, InitialState semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     StateMachine returns StateMachine
	 *     State returns StateMachine
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         states+=State* 
	 *         initialState=[InitialState|EString] 
	 *         historyState=[HistoryState|EString]? 
	 *         (events+=Event events+=Event*)? 
	 *         (transitions+=Transition transitions+=Transition*)? 
	 *         (actions+=Xmod_Action actions+=Xmod_Action*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_StateMachine(ISerializationContext context, StateMachine semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     State returns State
	 *     State_Impl returns State
	 *
	 * Constraint:
	 *     (name=EString (actions+=Xmod_Action actions+=Xmod_Action*)?)
	 * </pre>
	 */
	protected void sequence_State_Impl(ISerializationContext context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Transition returns Transition
	 *
	 * Constraint:
	 *     (source=[State|EString] target=[State|EString] event=[Event|EString] (actions+=Xmod_Action actions+=Xmod_Action*)?)
	 * </pre>
	 */
	protected void sequence_Transition(ISerializationContext context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_Action returns Xmod_Action
	 *
	 * Constraint:
	 *     (name=EString operations+=Xmod_OperationCall operations+=Xmod_OperationCall*)
	 * </pre>
	 */
	protected void sequence_Xmod_Action(ISerializationContext context, Xmod_Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_Exception returns Xmod_Exception
	 *
	 * Constraint:
	 *     (
	 *         (kind=Xmod_ExceptionKind_Unfiltered | (kind=Xmod_ExceptionKind_Filtered filter=EString)) 
	 *         calledOperation=Xmod_OperationDef? 
	 *         reaction=Xmod_ExceptionReaction
	 *     )
	 * </pre>
	 */
	protected void sequence_Xmod_Exception(ISerializationContext context, Xmod_Exception semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Xmod_OperationDef returns Xmod_Operation
	 *     Xmod_OperationCall returns Xmod_Operation
	 *
	 * Constraint:
	 *     (
	 *         name=EString 
	 *         (parametersTag+=EString parametersTag+=EString*)? 
	 *         objectTag=EString 
	 *         returnTag=EString? 
	 *         (exceptions+=Xmod_Exception exceptions+=Xmod_Exception*)?
	 *     )
	 * </pre>
	 */
	protected void sequence_Xmod_OperationDef(ISerializationContext context, Xmod_Operation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
