/*
 * generated by Xtext 2.40.0
 */
package org.xtext.scoping;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import stateMachine.CompositeState;
import stateMachine.State;
import stateMachine.StateMachine;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class StateMachineScopeProvider extends AbstractStateMachineScopeProvider {
	@Override
	public IScope getScope(EObject context, EReference reference) {
	    if(reference.getName().equals("source") || reference.getName().equals("target")) {
	        StateMachine machine = EcoreUtil2.getContainerOfType(context, StateMachine.class);
	        List<State> allStates = collectAllStates(machine);
	        return Scopes.scopeFor(allStates);
	    }
	    return super.getScope(context, reference);
	}

	private List<State> collectAllStates(StateMachine sm) {
	    List<State> states = new ArrayList<>();
	    for(State s : sm.getStates()) {
	        states.addAll(flatten(s));
	    }
	    return states;
	}

	private List<State> flatten(State s) {
	    List<State> result = new ArrayList<>();
	    result.add(s);
	    if(s instanceof CompositeState) {
	        for(State child : ((CompositeState)s).getStates()) {
	            result.addAll(flatten(child));
	        }
	    }
	    return result;
	}
}
