/**
 * generated by Xtext 2.40.0
 */
package org.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.services.StateMachineGrammarAccess;
import stateMachine.Event;
import stateMachine.State;
import stateMachine.StateMachine;
import stateMachine.Transition;
import stateMachine.Xmod_Action;

@SuppressWarnings("all")
public class StateMachineFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private StateMachineGrammarAccess _stateMachineGrammarAccess;

  protected void _format(final StateMachine stateMachine, @Extension final IFormattableDocument document) {
    EList<State> _states = stateMachine.getStates();
    for (final State state : _states) {
      document.<State>format(state);
    }
    EList<Xmod_Action> _actions = stateMachine.getActions();
    for (final Xmod_Action xmod_Action : _actions) {
      document.<Xmod_Action>format(xmod_Action);
    }
    EList<Event> _events = stateMachine.getEvents();
    for (final Event event : _events) {
      document.<Event>format(event);
    }
    EList<Transition> _transitions = stateMachine.getTransitions();
    for (final Transition transition : _transitions) {
      document.<Transition>format(transition);
    }
  }

  protected void _format(final State state, @Extension final IFormattableDocument document) {
    EList<Xmod_Action> _actions = state.getActions();
    for (final Xmod_Action xmod_Action : _actions) {
      document.<Xmod_Action>format(xmod_Action);
    }
  }

  @XbaseGenerated
  public void format(final Object stateMachine, final IFormattableDocument document) {
    if (stateMachine instanceof XtextResource) {
      _format((XtextResource)stateMachine, document);
      return;
    } else if (stateMachine instanceof StateMachine) {
      _format((StateMachine)stateMachine, document);
      return;
    } else if (stateMachine instanceof State) {
      _format((State)stateMachine, document);
      return;
    } else if (stateMachine instanceof EObject) {
      _format((EObject)stateMachine, document);
      return;
    } else if (stateMachine == null) {
      _format((Void)null, document);
      return;
    } else if (stateMachine != null) {
      _format(stateMachine, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(stateMachine, document).toString());
    }
  }
}
