/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalStateMachineParser;
import org.xtext.services.StateMachineGrammarAccess;

public class StateMachineParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(StateMachineGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, StateMachineGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getAlternatives_1(), "rule__Xmod_Exception__Alternatives_1");
			builder.put(grammarAccess.getXmod_ExceptionKind_UnfilteredAccess().getAlternatives(), "rule__Xmod_ExceptionKind_Unfiltered__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionReactionAccess().getAlternatives(), "rule__Xmod_ExceptionReaction__Alternatives");
			builder.put(grammarAccess.getXmod_ExceptionKindAccess().getAlternatives(), "rule__Xmod_ExceptionKind__Alternatives");
			builder.put(grammarAccess.getStateMachineAccess().getGroup(), "rule__StateMachine__Group__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_10(), "rule__StateMachine__Group_10__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_11(), "rule__StateMachine__Group_11__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_11_3(), "rule__StateMachine__Group_11_3__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_12(), "rule__StateMachine__Group_12__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_12_3(), "rule__StateMachine__Group_12_3__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_13(), "rule__StateMachine__Group_13__0");
			builder.put(grammarAccess.getStateMachineAccess().getGroup_13_1(), "rule__StateMachine__Group_13_1__0");
			builder.put(grammarAccess.getState_ImplAccess().getGroup(), "rule__State_Impl__Group__0");
			builder.put(grammarAccess.getState_ImplAccess().getGroup_2(), "rule__State_Impl__Group_2__0");
			builder.put(grammarAccess.getState_ImplAccess().getGroup_2_2(), "rule__State_Impl__Group_2_2__0");
			builder.put(grammarAccess.getInitialStateAccess().getGroup(), "rule__InitialState__Group__0");
			builder.put(grammarAccess.getInitialStateAccess().getGroup_2(), "rule__InitialState__Group_2__0");
			builder.put(grammarAccess.getHistoryStateAccess().getGroup(), "rule__HistoryState__Group__0");
			builder.put(grammarAccess.getEventAccess().getGroup(), "rule__Event__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_7(), "rule__Transition__Group_7__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_7_2(), "rule__Transition__Group_7_2__0");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getGroup(), "rule__CompositeState_Impl__Group__0");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getGroup_10(), "rule__CompositeState_Impl__Group_10__0");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getGroup_11(), "rule__CompositeState_Impl__Group_11__0");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getGroup_11_1(), "rule__CompositeState_Impl__Group_11_1__0");
			builder.put(grammarAccess.getXmod_ActionAccess().getGroup(), "rule__Xmod_Action__Group__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup(), "rule__Xmod_OperationDef__Group__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_2(), "rule__Xmod_OperationDef__Group_2__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_2_1(), "rule__Xmod_OperationDef__Group_2_1__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_6(), "rule__Xmod_OperationDef__Group_6__0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getGroup_7(), "rule__Xmod_OperationDef__Group_7__0");
			builder.put(grammarAccess.getXmod_OperationCallAccess().getGroup(), "rule__Xmod_OperationCall__Group__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup(), "rule__Xmod_Exception__Group__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup_1_1(), "rule__Xmod_Exception__Group_1_1__0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getGroup_2(), "rule__Xmod_Exception__Group_2__0");
			builder.put(grammarAccess.getStateMachineAccess().getNameAssignment_1(), "rule__StateMachine__NameAssignment_1");
			builder.put(grammarAccess.getStateMachineAccess().getStatesAssignment_5(), "rule__StateMachine__StatesAssignment_5");
			builder.put(grammarAccess.getStateMachineAccess().getInitialStateAssignment_9(), "rule__StateMachine__InitialStateAssignment_9");
			builder.put(grammarAccess.getStateMachineAccess().getHistoryStateAssignment_10_1(), "rule__StateMachine__HistoryStateAssignment_10_1");
			builder.put(grammarAccess.getStateMachineAccess().getEventsAssignment_11_2(), "rule__StateMachine__EventsAssignment_11_2");
			builder.put(grammarAccess.getStateMachineAccess().getEventsAssignment_11_3_1(), "rule__StateMachine__EventsAssignment_11_3_1");
			builder.put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_12_2(), "rule__StateMachine__TransitionsAssignment_12_2");
			builder.put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_12_3_1(), "rule__StateMachine__TransitionsAssignment_12_3_1");
			builder.put(grammarAccess.getStateMachineAccess().getActionsAssignment_13_0(), "rule__StateMachine__ActionsAssignment_13_0");
			builder.put(grammarAccess.getStateMachineAccess().getActionsAssignment_13_1_1(), "rule__StateMachine__ActionsAssignment_13_1_1");
			builder.put(grammarAccess.getState_ImplAccess().getNameAssignment_1(), "rule__State_Impl__NameAssignment_1");
			builder.put(grammarAccess.getState_ImplAccess().getActionsAssignment_2_1(), "rule__State_Impl__ActionsAssignment_2_1");
			builder.put(grammarAccess.getState_ImplAccess().getActionsAssignment_2_2_1(), "rule__State_Impl__ActionsAssignment_2_2_1");
			builder.put(grammarAccess.getInitialStateAccess().getNameAssignment_1(), "rule__InitialState__NameAssignment_1");
			builder.put(grammarAccess.getInitialStateAccess().getReferencedStateAssignment_2_1(), "rule__InitialState__ReferencedStateAssignment_2_1");
			builder.put(grammarAccess.getHistoryStateAccess().getNameAssignment_1(), "rule__HistoryState__NameAssignment_1");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_2(), "rule__Event__NameAssignment_2");
			builder.put(grammarAccess.getTransitionAccess().getSourceAssignment_2(), "rule__Transition__SourceAssignment_2");
			builder.put(grammarAccess.getTransitionAccess().getTargetAssignment_4(), "rule__Transition__TargetAssignment_4");
			builder.put(grammarAccess.getTransitionAccess().getEventAssignment_6(), "rule__Transition__EventAssignment_6");
			builder.put(grammarAccess.getTransitionAccess().getActionsAssignment_7_1(), "rule__Transition__ActionsAssignment_7_1");
			builder.put(grammarAccess.getTransitionAccess().getActionsAssignment_7_2_1(), "rule__Transition__ActionsAssignment_7_2_1");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getNameAssignment_1(), "rule__CompositeState_Impl__NameAssignment_1");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getStatesAssignment_5(), "rule__CompositeState_Impl__StatesAssignment_5");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getInitialStateAssignment_9(), "rule__CompositeState_Impl__InitialStateAssignment_9");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getHistoryStateAssignment_10_1(), "rule__CompositeState_Impl__HistoryStateAssignment_10_1");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getActionsAssignment_11_0(), "rule__CompositeState_Impl__ActionsAssignment_11_0");
			builder.put(grammarAccess.getCompositeState_ImplAccess().getActionsAssignment_11_1_1(), "rule__CompositeState_Impl__ActionsAssignment_11_1_1");
			builder.put(grammarAccess.getXmod_ActionAccess().getNameAssignment_1(), "rule__Xmod_Action__NameAssignment_1");
			builder.put(grammarAccess.getXmod_ActionAccess().getOperationsAssignment_3(), "rule__Xmod_Action__OperationsAssignment_3");
			builder.put(grammarAccess.getXmod_ActionAccess().getOperationsAssignment_4(), "rule__Xmod_Action__OperationsAssignment_4");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getNameAssignment_0(), "rule__Xmod_OperationDef__NameAssignment_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getParametersTagAssignment_2_0(), "rule__Xmod_OperationDef__ParametersTagAssignment_2_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getParametersTagAssignment_2_1_1(), "rule__Xmod_OperationDef__ParametersTagAssignment_2_1_1");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getObjectTagAssignment_5(), "rule__Xmod_OperationDef__ObjectTagAssignment_5");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getReturnTagAssignment_6_1(), "rule__Xmod_OperationDef__ReturnTagAssignment_6_1");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getExceptionsAssignment_7_0(), "rule__Xmod_OperationDef__ExceptionsAssignment_7_0");
			builder.put(grammarAccess.getXmod_OperationDefAccess().getExceptionsAssignment_7_1(), "rule__Xmod_OperationDef__ExceptionsAssignment_7_1");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getKindAssignment_1_0(), "rule__Xmod_Exception__KindAssignment_1_0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getKindAssignment_1_1_0(), "rule__Xmod_Exception__KindAssignment_1_1_0");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getFilterAssignment_1_1_2(), "rule__Xmod_Exception__FilterAssignment_1_1_2");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getCalledOperationAssignment_2_1(), "rule__Xmod_Exception__CalledOperationAssignment_2_1");
			builder.put(grammarAccess.getXmod_ExceptionAccess().getReactionAssignment_4(), "rule__Xmod_Exception__ReactionAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private StateMachineGrammarAccess grammarAccess;

	@Override
	protected InternalStateMachineParser createParser() {
		InternalStateMachineParser result = new InternalStateMachineParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StateMachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateMachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
