/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.STM.ui.internal.STMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StateMachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(STMActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		STMActivator activator = STMActivator.getInstance();
		return activator != null ? activator.getInjector(STMActivator.ORG_XTEXT_STATEMACHINE) : null;
	}

}
