/*
 * generated by Xtext 2.40.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class StateMachineGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateMachineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cStatesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatesStateParserRuleCall_5_0 = (RuleCall)cStatesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cStartsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cWithKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cInitialStateAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cInitialStateInitialStateCrossReference_9_0 = (CrossReference)cInitialStateAssignment_9.eContents().get(0);
		private final RuleCall cInitialStateInitialStateEStringParserRuleCall_9_0_1 = (RuleCall)cInitialStateInitialStateCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHistoryStateKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cHistoryStateAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cHistoryStateHistoryStateCrossReference_10_1_0 = (CrossReference)cHistoryStateAssignment_10_1.eContents().get(0);
		private final RuleCall cHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1 = (RuleCall)cHistoryStateHistoryStateCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cEventsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cEventsAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cEventsEventParserRuleCall_11_2_0 = (RuleCall)cEventsAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cEventsAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_11_3_1_0 = (RuleCall)cEventsAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cTransitionsKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cTransitionsAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cTransitionsTransitionParserRuleCall_12_2_0 = (RuleCall)cTransitionsAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cTransitionsAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cTransitionsTransitionParserRuleCall_12_3_1_0 = (RuleCall)cTransitionsAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Assignment cActionsAssignment_13_0 = (Assignment)cGroup_13.eContents().get(0);
		private final RuleCall cActionsXmod_ActionParserRuleCall_13_0_0 = (RuleCall)cActionsAssignment_13_0.eContents().get(0);
		private final Group cGroup_13_1 = (Group)cGroup_13.eContents().get(1);
		private final Keyword cCommaKeyword_13_1_0 = (Keyword)cGroup_13_1.eContents().get(0);
		private final Assignment cActionsAssignment_13_1_1 = (Assignment)cGroup_13_1.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_13_1_1_0 = (RuleCall)cActionsAssignment_13_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//StateMachine returns StateMachine:
		//    'StateMachine' name=EString '{'
		//        'states' '{' states+=State* '}'
		//        'starts' 'with' initialState=[InitialState|EString]
		//        ('historyState' historyState=[HistoryState|EString])?
		//        ('events' '{' events+=Event ( "," events+=Event)* '}' )?
		//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//        (actions+=Xmod_Action ( "," actions+=Xmod_Action)* )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'StateMachine' name=EString '{'
		//    'states' '{' states+=State* '}'
		//    'starts' 'with' initialState=[InitialState|EString]
		//    ('historyState' historyState=[HistoryState|EString])?
		//    ('events' '{' events+=Event ( "," events+=Event)* '}' )?
		//    ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		//    (actions+=Xmod_Action ( "," actions+=Xmod_Action)* )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'StateMachine'
		public Keyword getStateMachineKeyword_0() { return cStateMachineKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'states'
		public Keyword getStatesKeyword_3() { return cStatesKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//states+=State*
		public Assignment getStatesAssignment_5() { return cStatesAssignment_5; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_5_0() { return cStatesStateParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'starts'
		public Keyword getStartsKeyword_7() { return cStartsKeyword_7; }
		
		//'with'
		public Keyword getWithKeyword_8() { return cWithKeyword_8; }
		
		//initialState=[InitialState|EString]
		public Assignment getInitialStateAssignment_9() { return cInitialStateAssignment_9; }
		
		//[InitialState|EString]
		public CrossReference getInitialStateInitialStateCrossReference_9_0() { return cInitialStateInitialStateCrossReference_9_0; }
		
		//EString
		public RuleCall getInitialStateInitialStateEStringParserRuleCall_9_0_1() { return cInitialStateInitialStateEStringParserRuleCall_9_0_1; }
		
		//('historyState' historyState=[HistoryState|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'historyState'
		public Keyword getHistoryStateKeyword_10_0() { return cHistoryStateKeyword_10_0; }
		
		//historyState=[HistoryState|EString]
		public Assignment getHistoryStateAssignment_10_1() { return cHistoryStateAssignment_10_1; }
		
		//[HistoryState|EString]
		public CrossReference getHistoryStateHistoryStateCrossReference_10_1_0() { return cHistoryStateHistoryStateCrossReference_10_1_0; }
		
		//EString
		public RuleCall getHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1() { return cHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1; }
		
		//('events' '{' events+=Event ( "," events+=Event)* '}' )?
		public Group getGroup_11() { return cGroup_11; }
		
		//'events'
		public Keyword getEventsKeyword_11_0() { return cEventsKeyword_11_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }
		
		//events+=Event
		public Assignment getEventsAssignment_11_2() { return cEventsAssignment_11_2; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_11_2_0() { return cEventsEventParserRuleCall_11_2_0; }
		
		//( "," events+=Event)*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//events+=Event
		public Assignment getEventsAssignment_11_3_1() { return cEventsAssignment_11_3_1; }
		
		//Event
		public RuleCall getEventsEventParserRuleCall_11_3_1_0() { return cEventsEventParserRuleCall_11_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }
		
		//('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
		public Group getGroup_12() { return cGroup_12; }
		
		//'transitions'
		public Keyword getTransitionsKeyword_12_0() { return cTransitionsKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_12_2() { return cTransitionsAssignment_12_2; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_12_2_0() { return cTransitionsTransitionParserRuleCall_12_2_0; }
		
		//( "," transitions+=Transition)*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//transitions+=Transition
		public Assignment getTransitionsAssignment_12_3_1() { return cTransitionsAssignment_12_3_1; }
		
		//Transition
		public RuleCall getTransitionsTransitionParserRuleCall_12_3_1_0() { return cTransitionsTransitionParserRuleCall_12_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }
		
		//(actions+=Xmod_Action ( "," actions+=Xmod_Action)* )?
		public Group getGroup_13() { return cGroup_13; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_13_0() { return cActionsAssignment_13_0; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_13_0_0() { return cActionsXmod_ActionParserRuleCall_13_0_0; }
		
		//( "," actions+=Xmod_Action)*
		public Group getGroup_13_1() { return cGroup_13_1; }
		
		//","
		public Keyword getCommaKeyword_13_1_0() { return cCommaKeyword_13_1_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_13_1_1() { return cActionsAssignment_13_1_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_13_1_1_0() { return cActionsXmod_ActionParserRuleCall_13_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cState_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStateMachineParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCompositeState_ImplParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cInitialStateParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cHistoryStateParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//State returns State:
		//    State_Impl | StateMachine | CompositeState_Impl | InitialState | HistoryState;
		@Override public ParserRule getRule() { return rule; }
		
		//State_Impl | StateMachine | CompositeState_Impl | InitialState | HistoryState
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//State_Impl
		public RuleCall getState_ImplParserRuleCall_0() { return cState_ImplParserRuleCall_0; }
		
		//StateMachine
		public RuleCall getStateMachineParserRuleCall_1() { return cStateMachineParserRuleCall_1; }
		
		//CompositeState_Impl
		public RuleCall getCompositeState_ImplParserRuleCall_2() { return cCompositeState_ImplParserRuleCall_2; }
		
		//InitialState
		public RuleCall getInitialStateParserRuleCall_3() { return cInitialStateParserRuleCall_3; }
		
		//HistoryState
		public RuleCall getHistoryStateParserRuleCall_4() { return cHistoryStateParserRuleCall_4; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class State_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.State_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cActionsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_2_1_0 = (RuleCall)cActionsAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cActionsAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_2_2_1_0 = (RuleCall)cActionsAssignment_2_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//State_Impl returns State:
		//    'State' name=EString ('{'
		//        actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'State' name=EString ('{'
		//    actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'State'
		public Keyword getStateKeyword_0() { return cStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('{'
		//       actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//   '}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_2_1() { return cActionsAssignment_2_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_2_1_0() { return cActionsXmod_ActionParserRuleCall_2_1_0; }
		
		//( "," actions+=Xmod_Action)*
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//","
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_2_2_1() { return cActionsAssignment_2_2_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_2_2_1_0() { return cActionsXmod_ActionParserRuleCall_2_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class InitialStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.InitialState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitialStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cReferencesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cReferencedStateAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cReferencedStateStateCrossReference_2_1_0 = (CrossReference)cReferencedStateAssignment_2_1.eContents().get(0);
		private final RuleCall cReferencedStateStateEStringParserRuleCall_2_1_0_1 = (RuleCall)cReferencedStateStateCrossReference_2_1_0.eContents().get(1);
		
		//InitialState returns InitialState:
		//    'InitialState' name=EString ('references' referencedState=[State|EString])?;
		@Override public ParserRule getRule() { return rule; }
		
		//'InitialState' name=EString ('references' referencedState=[State|EString])?
		public Group getGroup() { return cGroup; }
		
		//'InitialState'
		public Keyword getInitialStateKeyword_0() { return cInitialStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//('references' referencedState=[State|EString])?
		public Group getGroup_2() { return cGroup_2; }
		
		//'references'
		public Keyword getReferencesKeyword_2_0() { return cReferencesKeyword_2_0; }
		
		//referencedState=[State|EString]
		public Assignment getReferencedStateAssignment_2_1() { return cReferencedStateAssignment_2_1; }
		
		//[State|EString]
		public CrossReference getReferencedStateStateCrossReference_2_1_0() { return cReferencedStateStateCrossReference_2_1_0; }
		
		//EString
		public RuleCall getReferencedStateStateEStringParserRuleCall_2_1_0_1() { return cReferencedStateStateEStringParserRuleCall_2_1_0_1; }
	}
	public class HistoryStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.HistoryState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHistoryStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//HistoryState returns HistoryState:
		//    'HistoryState' name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'HistoryState' name=EString
		public Group getGroup() { return cGroup; }
		
		//'HistoryState'
		public Keyword getHistoryStateKeyword_0() { return cHistoryStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEventKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Event returns Event:
		//    {Event}
		//    'Event'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Event}
		//'Event'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//{Event}
		public Action getEventAction_0() { return cEventAction_0; }
		
		//'Event'
		public Keyword getEventKeyword_1() { return cEventKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cSourceStateCrossReference_2_0 = (CrossReference)cSourceAssignment_2.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_2_0_1 = (RuleCall)cSourceStateCrossReference_2_0.eContents().get(1);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTargetStateCrossReference_4_0 = (CrossReference)cTargetAssignment_4.eContents().get(0);
		private final RuleCall cTargetStateEStringParserRuleCall_4_0_1 = (RuleCall)cTargetStateCrossReference_4_0.eContents().get(1);
		private final Keyword cOnKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cEventAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cEventEventCrossReference_6_0 = (CrossReference)cEventAssignment_6.eContents().get(0);
		private final RuleCall cEventEventEStringParserRuleCall_6_0_1 = (RuleCall)cEventEventCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cActionsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_7_1_0 = (RuleCall)cActionsAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cActionsAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_7_2_1_0 = (RuleCall)cActionsAssignment_7_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//Transition returns Transition:
		//    'Transition' 'from' source=[State|EString] 'to' target=[State|EString] 'on' event=[Event|EString] ('{'
		//        actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Transition' 'from' source=[State|EString] 'to' target=[State|EString] 'on' event=[Event|EString] ('{'
		//    actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'Transition'
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }
		
		//'from'
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//source=[State|EString]
		public Assignment getSourceAssignment_2() { return cSourceAssignment_2; }
		
		//[State|EString]
		public CrossReference getSourceStateCrossReference_2_0() { return cSourceStateCrossReference_2_0; }
		
		//EString
		public RuleCall getSourceStateEStringParserRuleCall_2_0_1() { return cSourceStateEStringParserRuleCall_2_0_1; }
		
		//'to'
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//target=[State|EString]
		public Assignment getTargetAssignment_4() { return cTargetAssignment_4; }
		
		//[State|EString]
		public CrossReference getTargetStateCrossReference_4_0() { return cTargetStateCrossReference_4_0; }
		
		//EString
		public RuleCall getTargetStateEStringParserRuleCall_4_0_1() { return cTargetStateEStringParserRuleCall_4_0_1; }
		
		//'on'
		public Keyword getOnKeyword_5() { return cOnKeyword_5; }
		
		//event=[Event|EString]
		public Assignment getEventAssignment_6() { return cEventAssignment_6; }
		
		//[Event|EString]
		public CrossReference getEventEventCrossReference_6_0() { return cEventEventCrossReference_6_0; }
		
		//EString
		public RuleCall getEventEventEStringParserRuleCall_6_0_1() { return cEventEventEStringParserRuleCall_6_0_1; }
		
		//('{'
		//       actions+=Xmod_Action ( "," actions+=Xmod_Action)*
		//   '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_0() { return cLeftCurlyBracketKeyword_7_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_7_1() { return cActionsAssignment_7_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_7_1_0() { return cActionsXmod_ActionParserRuleCall_7_1_0; }
		
		//( "," actions+=Xmod_Action)*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//","
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_7_2_1() { return cActionsAssignment_7_2_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_7_2_1_0() { return cActionsXmod_ActionParserRuleCall_7_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}
	public class CompositeState_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.CompositeState_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCompositeStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cStatesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStatesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStatesStateParserRuleCall_5_0 = (RuleCall)cStatesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cStartsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cWithKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cInitialStateAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cInitialStateInitialStateCrossReference_9_0 = (CrossReference)cInitialStateAssignment_9.eContents().get(0);
		private final RuleCall cInitialStateInitialStateEStringParserRuleCall_9_0_1 = (RuleCall)cInitialStateInitialStateCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cHistoryStateKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cHistoryStateAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cHistoryStateHistoryStateCrossReference_10_1_0 = (CrossReference)cHistoryStateAssignment_10_1.eContents().get(0);
		private final RuleCall cHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1 = (RuleCall)cHistoryStateHistoryStateCrossReference_10_1_0.eContents().get(1);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Assignment cActionsAssignment_11_0 = (Assignment)cGroup_11.eContents().get(0);
		private final RuleCall cActionsXmod_ActionParserRuleCall_11_0_0 = (RuleCall)cActionsAssignment_11_0.eContents().get(0);
		private final Group cGroup_11_1 = (Group)cGroup_11.eContents().get(1);
		private final Keyword cCommaKeyword_11_1_0 = (Keyword)cGroup_11_1.eContents().get(0);
		private final Assignment cActionsAssignment_11_1_1 = (Assignment)cGroup_11_1.eContents().get(1);
		private final RuleCall cActionsXmod_ActionParserRuleCall_11_1_1_0 = (RuleCall)cActionsAssignment_11_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//CompositeState_Impl returns CompositeState:
		//    'CompositeState' name=EString '{'
		//        'states' '{' states+=State* '}'
		//        'starts' 'with' initialState=[InitialState|EString]
		//        ('historyState' historyState=[HistoryState|EString])?
		//        (actions+=Xmod_Action ( "," actions+=Xmod_Action)*)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'CompositeState' name=EString '{'
		//    'states' '{' states+=State* '}'
		//    'starts' 'with' initialState=[InitialState|EString]
		//    ('historyState' historyState=[HistoryState|EString])?
		//    (actions+=Xmod_Action ( "," actions+=Xmod_Action)*)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'CompositeState'
		public Keyword getCompositeStateKeyword_0() { return cCompositeStateKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'states'
		public Keyword getStatesKeyword_3() { return cStatesKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//states+=State*
		public Assignment getStatesAssignment_5() { return cStatesAssignment_5; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_5_0() { return cStatesStateParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'starts'
		public Keyword getStartsKeyword_7() { return cStartsKeyword_7; }
		
		//'with'
		public Keyword getWithKeyword_8() { return cWithKeyword_8; }
		
		//initialState=[InitialState|EString]
		public Assignment getInitialStateAssignment_9() { return cInitialStateAssignment_9; }
		
		//[InitialState|EString]
		public CrossReference getInitialStateInitialStateCrossReference_9_0() { return cInitialStateInitialStateCrossReference_9_0; }
		
		//EString
		public RuleCall getInitialStateInitialStateEStringParserRuleCall_9_0_1() { return cInitialStateInitialStateEStringParserRuleCall_9_0_1; }
		
		//('historyState' historyState=[HistoryState|EString])?
		public Group getGroup_10() { return cGroup_10; }
		
		//'historyState'
		public Keyword getHistoryStateKeyword_10_0() { return cHistoryStateKeyword_10_0; }
		
		//historyState=[HistoryState|EString]
		public Assignment getHistoryStateAssignment_10_1() { return cHistoryStateAssignment_10_1; }
		
		//[HistoryState|EString]
		public CrossReference getHistoryStateHistoryStateCrossReference_10_1_0() { return cHistoryStateHistoryStateCrossReference_10_1_0; }
		
		//EString
		public RuleCall getHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1() { return cHistoryStateHistoryStateEStringParserRuleCall_10_1_0_1; }
		
		//(actions+=Xmod_Action ( "," actions+=Xmod_Action)*)?
		public Group getGroup_11() { return cGroup_11; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_11_0() { return cActionsAssignment_11_0; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_11_0_0() { return cActionsXmod_ActionParserRuleCall_11_0_0; }
		
		//( "," actions+=Xmod_Action)*
		public Group getGroup_11_1() { return cGroup_11_1; }
		
		//","
		public Keyword getCommaKeyword_11_1_0() { return cCommaKeyword_11_1_0; }
		
		//actions+=Xmod_Action
		public Assignment getActionsAssignment_11_1_1() { return cActionsAssignment_11_1_1; }
		
		//Xmod_Action
		public RuleCall getActionsXmod_ActionParserRuleCall_11_1_1_0() { return cActionsXmod_ActionParserRuleCall_11_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class Xmod_ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperationsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperationsXmod_OperationCallParserRuleCall_3_0 = (RuleCall)cOperationsAssignment_3.eContents().get(0);
		private final Assignment cOperationsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cOperationsXmod_OperationCallParserRuleCall_4_0 = (RuleCall)cOperationsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Xmod_Action returns Xmod_Action:
		//    'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}'
		public Group getGroup() { return cGroup; }
		
		//'Action'
		public Keyword getActionKeyword_0() { return cActionKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//operations+=Xmod_OperationCall
		public Assignment getOperationsAssignment_3() { return cOperationsAssignment_3; }
		
		//Xmod_OperationCall
		public RuleCall getOperationsXmod_OperationCallParserRuleCall_3_0() { return cOperationsXmod_OperationCallParserRuleCall_3_0; }
		
		//(operations+=Xmod_OperationCall)*
		public Assignment getOperationsAssignment_4() { return cOperationsAssignment_4; }
		
		//Xmod_OperationCall
		public RuleCall getOperationsXmod_OperationCallParserRuleCall_4_0() { return cOperationsXmod_OperationCallParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class Xmod_OperationDefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_OperationDef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cParametersTagAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cParametersTagEStringParserRuleCall_2_0_0 = (RuleCall)cParametersTagAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cCommaKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cParametersTagAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cParametersTagEStringParserRuleCall_2_1_1_0 = (RuleCall)cParametersTagAssignment_2_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cObjectTagAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cObjectTagEStringParserRuleCall_5_0 = (RuleCall)cObjectTagAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cReturnsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cReturnTagAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cReturnTagEStringParserRuleCall_6_1_0 = (RuleCall)cReturnTagAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Assignment cExceptionsAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final RuleCall cExceptionsXmod_ExceptionParserRuleCall_7_0_0 = (RuleCall)cExceptionsAssignment_7_0.eContents().get(0);
		private final Assignment cExceptionsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cExceptionsXmod_ExceptionParserRuleCall_7_1_0 = (RuleCall)cExceptionsAssignment_7_1.eContents().get(0);
		
		//Xmod_OperationDef returns Xmod_Operation:
		//    name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
		//        'on' objectTag=EString ('returns' returnTag=EString)?
		//        (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
		//    'on' objectTag=EString ('returns' returnTag=EString)?
		//    (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//( parametersTag+=EString ( "," parametersTag+=EString )* )?
		public Group getGroup_2() { return cGroup_2; }
		
		//parametersTag+=EString
		public Assignment getParametersTagAssignment_2_0() { return cParametersTagAssignment_2_0; }
		
		//EString
		public RuleCall getParametersTagEStringParserRuleCall_2_0_0() { return cParametersTagEStringParserRuleCall_2_0_0; }
		
		//( "," parametersTag+=EString )*
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//","
		public Keyword getCommaKeyword_2_1_0() { return cCommaKeyword_2_1_0; }
		
		//parametersTag+=EString
		public Assignment getParametersTagAssignment_2_1_1() { return cParametersTagAssignment_2_1_1; }
		
		//EString
		public RuleCall getParametersTagEStringParserRuleCall_2_1_1_0() { return cParametersTagEStringParserRuleCall_2_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'on'
		public Keyword getOnKeyword_4() { return cOnKeyword_4; }
		
		//objectTag=EString
		public Assignment getObjectTagAssignment_5() { return cObjectTagAssignment_5; }
		
		//EString
		public RuleCall getObjectTagEStringParserRuleCall_5_0() { return cObjectTagEStringParserRuleCall_5_0; }
		
		//('returns' returnTag=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'returns'
		public Keyword getReturnsKeyword_6_0() { return cReturnsKeyword_6_0; }
		
		//returnTag=EString
		public Assignment getReturnTagAssignment_6_1() { return cReturnTagAssignment_6_1; }
		
		//EString
		public RuleCall getReturnTagEStringParserRuleCall_6_1_0() { return cReturnTagEStringParserRuleCall_6_1_0; }
		
		//(exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?
		public Group getGroup_7() { return cGroup_7; }
		
		//exceptions+=Xmod_Exception
		public Assignment getExceptionsAssignment_7_0() { return cExceptionsAssignment_7_0; }
		
		//Xmod_Exception
		public RuleCall getExceptionsXmod_ExceptionParserRuleCall_7_0_0() { return cExceptionsXmod_ExceptionParserRuleCall_7_0_0; }
		
		//(exceptions+=Xmod_Exception)*
		public Assignment getExceptionsAssignment_7_1() { return cExceptionsAssignment_7_1; }
		
		//Xmod_Exception
		public RuleCall getExceptionsXmod_ExceptionParserRuleCall_7_1_0() { return cExceptionsXmod_ExceptionParserRuleCall_7_1_0; }
	}
	public class Xmod_OperationCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_OperationCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cXmod_OperationDefParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Xmod_OperationCall returns Xmod_Operation:
		//    'call' Xmod_OperationDef ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'call' Xmod_OperationDef ';'
		public Group getGroup() { return cGroup; }
		
		//'call'
		public Keyword getCallKeyword_0() { return cCallKeyword_0; }
		
		//Xmod_OperationDef
		public RuleCall getXmod_OperationDefParserRuleCall_1() { return cXmod_OperationDefParserRuleCall_1; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class Xmod_ExceptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_Exception");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOnErrorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cKindAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0 = (RuleCall)cKindAssignment_1_0.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cKindAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final RuleCall cKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0 = (RuleCall)cKindAssignment_1_1_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cFilterAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cFilterEStringParserRuleCall_1_1_2_0 = (RuleCall)cFilterAssignment_1_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_1_3 = (Keyword)cGroup_1_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCallKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cCalledOperationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCalledOperationXmod_OperationDefParserRuleCall_2_1_0 = (RuleCall)cCalledOperationAssignment_2_1.eContents().get(0);
		private final Keyword cThenKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cReactionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cReactionXmod_ExceptionReactionEnumRuleCall_4_0 = (RuleCall)cReactionAssignment_4.eContents().get(0);
		
		//Xmod_Exception returns Xmod_Exception:
		//    'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		//    ('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction;
		@Override public ParserRule getRule() { return rule; }
		
		//'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		//('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction
		public Group getGroup() { return cGroup; }
		
		//'onError'
		public Keyword getOnErrorKeyword_0() { return cOnErrorKeyword_0; }
		
		//(kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//kind=Xmod_ExceptionKind_Unfiltered
		public Assignment getKindAssignment_1_0() { return cKindAssignment_1_0; }
		
		//Xmod_ExceptionKind_Unfiltered
		public RuleCall getKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0() { return cKindXmod_ExceptionKind_UnfilteredParserRuleCall_1_0_0; }
		
		//kind=Xmod_ExceptionKind_Filtered '('filter=EString')'
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//kind=Xmod_ExceptionKind_Filtered
		public Assignment getKindAssignment_1_1_0() { return cKindAssignment_1_1_0; }
		
		//Xmod_ExceptionKind_Filtered
		public RuleCall getKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0() { return cKindXmod_ExceptionKind_FilteredParserRuleCall_1_1_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1_1() { return cLeftParenthesisKeyword_1_1_1; }
		
		//filter=EString
		public Assignment getFilterAssignment_1_1_2() { return cFilterAssignment_1_1_2; }
		
		//EString
		public RuleCall getFilterEStringParserRuleCall_1_1_2_0() { return cFilterEStringParserRuleCall_1_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1_3() { return cRightParenthesisKeyword_1_1_3; }
		
		//('call' calledOperation=Xmod_OperationDef)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'call'
		public Keyword getCallKeyword_2_0() { return cCallKeyword_2_0; }
		
		//calledOperation=Xmod_OperationDef
		public Assignment getCalledOperationAssignment_2_1() { return cCalledOperationAssignment_2_1; }
		
		//Xmod_OperationDef
		public RuleCall getCalledOperationXmod_OperationDefParserRuleCall_2_1_0() { return cCalledOperationXmod_OperationDefParserRuleCall_2_1_0; }
		
		//'then'
		public Keyword getThenKeyword_3() { return cThenKeyword_3; }
		
		//reaction=Xmod_ExceptionReaction
		public Assignment getReactionAssignment_4() { return cReactionAssignment_4; }
		
		//Xmod_ExceptionReaction
		public RuleCall getReactionXmod_ExceptionReactionEnumRuleCall_4_0() { return cReactionXmod_ExceptionReactionEnumRuleCall_4_0; }
	}
	public class Xmod_ExceptionKind_FilteredElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_ExceptionKind_Filtered");
		private final Keyword cMethodExceptionKeyword = (Keyword)rule.eContents().get(1);
		
		//Xmod_ExceptionKind_Filtered returns Xmod_ExceptionKind:
		//    'methodException';
		@Override public ParserRule getRule() { return rule; }
		
		//'methodException'
		public Keyword getMethodExceptionKeyword() { return cMethodExceptionKeyword; }
	}
	public class Xmod_ExceptionKind_UnfilteredElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_ExceptionKind_Unfiltered");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cOtherKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cUnknownNamespaceKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cObjectNotFoundKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cMethodNotFoundKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cParametersNotMatchingKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cReturnTypeNotMatchingKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Xmod_ExceptionKind_Unfiltered returns Xmod_ExceptionKind:
		//    'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching';
		@Override public ParserRule getRule() { return rule; }
		
		//'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'other'
		public Keyword getOtherKeyword_0() { return cOtherKeyword_0; }
		
		//'unknownNamespace'
		public Keyword getUnknownNamespaceKeyword_1() { return cUnknownNamespaceKeyword_1; }
		
		//'objectNotFound'
		public Keyword getObjectNotFoundKeyword_2() { return cObjectNotFoundKeyword_2; }
		
		//'methodNotFound'
		public Keyword getMethodNotFoundKeyword_3() { return cMethodNotFoundKeyword_3; }
		
		//'parametersNotMatching'
		public Keyword getParametersNotMatchingKeyword_4() { return cParametersNotMatchingKeyword_4; }
		
		//'returnTypeNotMatching'
		public Keyword getReturnTypeNotMatchingKeyword_5() { return cReturnTypeNotMatchingKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	
	public class Xmod_ExceptionReactionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_ExceptionReaction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cContinueEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cContinueContinueKeyword_0_0 = (Keyword)cContinueEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSkipEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSkipSkipKeyword_1_0 = (Keyword)cSkipEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cExitEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cExitExitKeyword_2_0 = (Keyword)cExitEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Xmod_ExceptionReaction:
		//    continue | skip | exit;
		public EnumRule getRule() { return rule; }
		
		//continue | skip | exit
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//continue
		public EnumLiteralDeclaration getContinueEnumLiteralDeclaration_0() { return cContinueEnumLiteralDeclaration_0; }
		
		public Keyword getContinueContinueKeyword_0_0() { return cContinueContinueKeyword_0_0; }
		
		//skip
		public EnumLiteralDeclaration getSkipEnumLiteralDeclaration_1() { return cSkipEnumLiteralDeclaration_1; }
		
		public Keyword getSkipSkipKeyword_1_0() { return cSkipSkipKeyword_1_0; }
		
		//exit
		public EnumLiteralDeclaration getExitEnumLiteralDeclaration_2() { return cExitEnumLiteralDeclaration_2; }
		
		public Keyword getExitExitKeyword_2_0() { return cExitExitKeyword_2_0; }
	}
	public class Xmod_ExceptionKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.StateMachine.Xmod_ExceptionKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOtherEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOtherOtherKeyword_0_0 = (Keyword)cOtherEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cUnknownNamespaceEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cUnknownNamespaceUnknownNamespaceKeyword_1_0 = (Keyword)cUnknownNamespaceEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cObjectNotFoundEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cObjectNotFoundObjectNotFoundKeyword_2_0 = (Keyword)cObjectNotFoundEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMethodNotFoundEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMethodNotFoundMethodNotFoundKeyword_3_0 = (Keyword)cMethodNotFoundEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cParametersNotMatchingEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cParametersNotMatchingParametersNotMatchingKeyword_4_0 = (Keyword)cParametersNotMatchingEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cReturnTypeNotMatchingEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0 = (Keyword)cReturnTypeNotMatchingEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cMethodExceptionEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cMethodExceptionMethodExceptionKeyword_6_0 = (Keyword)cMethodExceptionEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Xmod_ExceptionKind:
		//    other = 'other' |
		//    unknownNamespace = 'unknownNamespace' |
		//    objectNotFound = 'objectNotFound' |
		//    methodNotFound = 'methodNotFound' |
		//    parametersNotMatching = 'parametersNotMatching' |
		//    returnTypeNotMatching = 'returnTypeNotMatching' |
		//    methodException = 'methodException';
		public EnumRule getRule() { return rule; }
		
		//other = 'other' |
		//unknownNamespace = 'unknownNamespace' |
		//objectNotFound = 'objectNotFound' |
		//methodNotFound = 'methodNotFound' |
		//parametersNotMatching = 'parametersNotMatching' |
		//returnTypeNotMatching = 'returnTypeNotMatching' |
		//methodException = 'methodException'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//other = 'other'
		public EnumLiteralDeclaration getOtherEnumLiteralDeclaration_0() { return cOtherEnumLiteralDeclaration_0; }
		
		//'other'
		public Keyword getOtherOtherKeyword_0_0() { return cOtherOtherKeyword_0_0; }
		
		//unknownNamespace = 'unknownNamespace'
		public EnumLiteralDeclaration getUnknownNamespaceEnumLiteralDeclaration_1() { return cUnknownNamespaceEnumLiteralDeclaration_1; }
		
		//'unknownNamespace'
		public Keyword getUnknownNamespaceUnknownNamespaceKeyword_1_0() { return cUnknownNamespaceUnknownNamespaceKeyword_1_0; }
		
		//objectNotFound = 'objectNotFound'
		public EnumLiteralDeclaration getObjectNotFoundEnumLiteralDeclaration_2() { return cObjectNotFoundEnumLiteralDeclaration_2; }
		
		//'objectNotFound'
		public Keyword getObjectNotFoundObjectNotFoundKeyword_2_0() { return cObjectNotFoundObjectNotFoundKeyword_2_0; }
		
		//methodNotFound = 'methodNotFound'
		public EnumLiteralDeclaration getMethodNotFoundEnumLiteralDeclaration_3() { return cMethodNotFoundEnumLiteralDeclaration_3; }
		
		//'methodNotFound'
		public Keyword getMethodNotFoundMethodNotFoundKeyword_3_0() { return cMethodNotFoundMethodNotFoundKeyword_3_0; }
		
		//parametersNotMatching = 'parametersNotMatching'
		public EnumLiteralDeclaration getParametersNotMatchingEnumLiteralDeclaration_4() { return cParametersNotMatchingEnumLiteralDeclaration_4; }
		
		//'parametersNotMatching'
		public Keyword getParametersNotMatchingParametersNotMatchingKeyword_4_0() { return cParametersNotMatchingParametersNotMatchingKeyword_4_0; }
		
		//returnTypeNotMatching = 'returnTypeNotMatching'
		public EnumLiteralDeclaration getReturnTypeNotMatchingEnumLiteralDeclaration_5() { return cReturnTypeNotMatchingEnumLiteralDeclaration_5; }
		
		//'returnTypeNotMatching'
		public Keyword getReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0() { return cReturnTypeNotMatchingReturnTypeNotMatchingKeyword_5_0; }
		
		//methodException = 'methodException'
		public EnumLiteralDeclaration getMethodExceptionEnumLiteralDeclaration_6() { return cMethodExceptionEnumLiteralDeclaration_6; }
		
		//'methodException'
		public Keyword getMethodExceptionMethodExceptionKeyword_6_0() { return cMethodExceptionMethodExceptionKeyword_6_0; }
	}
	
	private final StateMachineElements pStateMachine;
	private final StateElements pState;
	private final EBooleanElements pEBoolean;
	private final State_ImplElements pState_Impl;
	private final InitialStateElements pInitialState;
	private final HistoryStateElements pHistoryState;
	private final EventElements pEvent;
	private final TransitionElements pTransition;
	private final CompositeState_ImplElements pCompositeState_Impl;
	private final Xmod_ActionElements pXmod_Action;
	private final Xmod_OperationDefElements pXmod_OperationDef;
	private final Xmod_OperationCallElements pXmod_OperationCall;
	private final Xmod_ExceptionElements pXmod_Exception;
	private final Xmod_ExceptionReactionElements eXmod_ExceptionReaction;
	private final Xmod_ExceptionKindElements eXmod_ExceptionKind;
	private final Xmod_ExceptionKind_FilteredElements pXmod_ExceptionKind_Filtered;
	private final Xmod_ExceptionKind_UnfilteredElements pXmod_ExceptionKind_Unfiltered;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public StateMachineGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStateMachine = new StateMachineElements();
		this.pState = new StateElements();
		this.pEBoolean = new EBooleanElements();
		this.pState_Impl = new State_ImplElements();
		this.pInitialState = new InitialStateElements();
		this.pHistoryState = new HistoryStateElements();
		this.pEvent = new EventElements();
		this.pTransition = new TransitionElements();
		this.pCompositeState_Impl = new CompositeState_ImplElements();
		this.pXmod_Action = new Xmod_ActionElements();
		this.pXmod_OperationDef = new Xmod_OperationDefElements();
		this.pXmod_OperationCall = new Xmod_OperationCallElements();
		this.pXmod_Exception = new Xmod_ExceptionElements();
		this.eXmod_ExceptionReaction = new Xmod_ExceptionReactionElements();
		this.eXmod_ExceptionKind = new Xmod_ExceptionKindElements();
		this.pXmod_ExceptionKind_Filtered = new Xmod_ExceptionKind_FilteredElements();
		this.pXmod_ExceptionKind_Unfiltered = new Xmod_ExceptionKind_UnfilteredElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.StateMachine".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine returns StateMachine:
	//    'StateMachine' name=EString '{'
	//        'states' '{' states+=State* '}'
	//        'starts' 'with' initialState=[InitialState|EString]
	//        ('historyState' historyState=[HistoryState|EString])?
	//        ('events' '{' events+=Event ( "," events+=Event)* '}' )?
	//        ('transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' )?
	//        (actions+=Xmod_Action ( "," actions+=Xmod_Action)* )?
	//    '}';
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}
	
	//State returns State:
	//    State_Impl | StateMachine | CompositeState_Impl | InitialState | HistoryState;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//State_Impl returns State:
	//    'State' name=EString ('{'
	//        actions+=Xmod_Action ( "," actions+=Xmod_Action)*
	//    '}')?;
	public State_ImplElements getState_ImplAccess() {
		return pState_Impl;
	}
	
	public ParserRule getState_ImplRule() {
		return getState_ImplAccess().getRule();
	}
	
	//InitialState returns InitialState:
	//    'InitialState' name=EString ('references' referencedState=[State|EString])?;
	public InitialStateElements getInitialStateAccess() {
		return pInitialState;
	}
	
	public ParserRule getInitialStateRule() {
		return getInitialStateAccess().getRule();
	}
	
	//HistoryState returns HistoryState:
	//    'HistoryState' name=EString;
	public HistoryStateElements getHistoryStateAccess() {
		return pHistoryState;
	}
	
	public ParserRule getHistoryStateRule() {
		return getHistoryStateAccess().getRule();
	}
	
	//Event returns Event:
	//    {Event}
	//    'Event'
	//    name=EString;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}
	
	//Transition returns Transition:
	//    'Transition' 'from' source=[State|EString] 'to' target=[State|EString] 'on' event=[Event|EString] ('{'
	//        actions+=Xmod_Action ( "," actions+=Xmod_Action)*
	//    '}')?;
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}
	
	//CompositeState_Impl returns CompositeState:
	//    'CompositeState' name=EString '{'
	//        'states' '{' states+=State* '}'
	//        'starts' 'with' initialState=[InitialState|EString]
	//        ('historyState' historyState=[HistoryState|EString])?
	//        (actions+=Xmod_Action ( "," actions+=Xmod_Action)*)?
	//    '}';
	public CompositeState_ImplElements getCompositeState_ImplAccess() {
		return pCompositeState_Impl;
	}
	
	public ParserRule getCompositeState_ImplRule() {
		return getCompositeState_ImplAccess().getRule();
	}
	
	//Xmod_Action returns Xmod_Action:
	//    'Action' name=EString '{' operations+=Xmod_OperationCall (operations+=Xmod_OperationCall)* '}';
	public Xmod_ActionElements getXmod_ActionAccess() {
		return pXmod_Action;
	}
	
	public ParserRule getXmod_ActionRule() {
		return getXmod_ActionAccess().getRule();
	}
	
	//Xmod_OperationDef returns Xmod_Operation:
	//    name=EString'('( parametersTag+=EString ( "," parametersTag+=EString )* )?')'
	//        'on' objectTag=EString ('returns' returnTag=EString)?
	//        (exceptions+=Xmod_Exception (exceptions+=Xmod_Exception)* )?;
	public Xmod_OperationDefElements getXmod_OperationDefAccess() {
		return pXmod_OperationDef;
	}
	
	public ParserRule getXmod_OperationDefRule() {
		return getXmod_OperationDefAccess().getRule();
	}
	
	//Xmod_OperationCall returns Xmod_Operation:
	//    'call' Xmod_OperationDef ';';
	public Xmod_OperationCallElements getXmod_OperationCallAccess() {
		return pXmod_OperationCall;
	}
	
	public ParserRule getXmod_OperationCallRule() {
		return getXmod_OperationCallAccess().getRule();
	}
	
	//Xmod_Exception returns Xmod_Exception:
	//    'onError' (kind=Xmod_ExceptionKind_Unfiltered | kind=Xmod_ExceptionKind_Filtered '('filter=EString')')
	//    ('call' calledOperation=Xmod_OperationDef)? 'then' reaction=Xmod_ExceptionReaction;
	public Xmod_ExceptionElements getXmod_ExceptionAccess() {
		return pXmod_Exception;
	}
	
	public ParserRule getXmod_ExceptionRule() {
		return getXmod_ExceptionAccess().getRule();
	}
	
	//enum Xmod_ExceptionReaction:
	//    continue | skip | exit;
	public Xmod_ExceptionReactionElements getXmod_ExceptionReactionAccess() {
		return eXmod_ExceptionReaction;
	}
	
	public EnumRule getXmod_ExceptionReactionRule() {
		return getXmod_ExceptionReactionAccess().getRule();
	}
	
	//enum Xmod_ExceptionKind:
	//    other = 'other' |
	//    unknownNamespace = 'unknownNamespace' |
	//    objectNotFound = 'objectNotFound' |
	//    methodNotFound = 'methodNotFound' |
	//    parametersNotMatching = 'parametersNotMatching' |
	//    returnTypeNotMatching = 'returnTypeNotMatching' |
	//    methodException = 'methodException';
	public Xmod_ExceptionKindElements getXmod_ExceptionKindAccess() {
		return eXmod_ExceptionKind;
	}
	
	public EnumRule getXmod_ExceptionKindRule() {
		return getXmod_ExceptionKindAccess().getRule();
	}
	
	//Xmod_ExceptionKind_Filtered returns Xmod_ExceptionKind:
	//    'methodException';
	public Xmod_ExceptionKind_FilteredElements getXmod_ExceptionKind_FilteredAccess() {
		return pXmod_ExceptionKind_Filtered;
	}
	
	public ParserRule getXmod_ExceptionKind_FilteredRule() {
		return getXmod_ExceptionKind_FilteredAccess().getRule();
	}
	
	//Xmod_ExceptionKind_Unfiltered returns Xmod_ExceptionKind:
	//    'other' | 'unknownNamespace' | 'objectNotFound' | 'methodNotFound' | 'parametersNotMatching' | 'returnTypeNotMatching';
	public Xmod_ExceptionKind_UnfilteredElements getXmod_ExceptionKind_UnfilteredAccess() {
		return pXmod_ExceptionKind_Unfiltered;
	}
	
	public ParserRule getXmod_ExceptionKind_UnfilteredRule() {
		return getXmod_ExceptionKind_UnfilteredAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
