/*
 * generated by Xtext 2.40.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.STM.ui.internal.STMActivator;

public class StateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return STMActivator.getInstance().getInjector("org.xtext.StateMachine");
	}

}
