/*
 * generated by Xtext 2.40.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStateMachineScopeProvider extends DelegatingScopeProvider {
}
